"use client";

import Link from "next/link";
import { Check, ChevronRight, CircleUserRound, Copy, ExternalLink, MapPin, Pencil, Share2, Truck, X } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Labels = Record<string, string>;
type Filter = "all" | "inProgress" | "delivered" | "cancelled";

const orders = [
  { id: "#KS-10234", date: "16 août 2026", status: "inProgress" as const, total: "28 000 FCFA", products: ["GABI.", "KEMI 01", "NOA"] },
  { id: "#KS-10198", date: "2 août 2026", status: "delivered" as const, total: "12 000 FCFA", products: ["GABI."] },
  { id: "#KS-10150", date: "20 juil. 2026", status: "cancelled" as const, total: "15 000 FCFA", products: ["KEMI 02", "SIRA"] },
];

export function AccountView({ labels }: { labels: Labels }) {
  const [section, setSection] = useState("orders");
  const [filter, setFilter] = useState<Filter>("all");
  const [selectedOrder, setSelectedOrder] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [saved, setSaved] = useState(false);
  const filteredOrders = filter === "all" ? orders : orders.filter((order) => order.status === filter);

  return <main className="account-page"><div className="account-shell"><header className="account-hero"><div><span className="eyebrow">KEMI SHOES / {labels.title}</span><h1>{labels.welcome}</h1></div><div className="account-avatar"><CircleUserRound aria-hidden="true" /></div></header><Tabs value={section} onValueChange={setSection} className="account-tabs"><TabsList variant="line" className="account-tabs-list"><TabsTrigger value="orders">{labels.orders}</TabsTrigger><TabsTrigger value="information">{labels.information}</TabsTrigger></TabsList><TabsContent value="orders" className="account-content"><div className="account-section-heading"><div><span className="section-kicker">02 / 04</span><h2>{labels.orders}</h2></div><span className="account-count">{orders.length} {labels.order}</span></div><Tabs value={filter} onValueChange={(value) => setFilter(value as Filter)} className="order-filters"><TabsList variant="line"><TabsTrigger value="all">{labels.all}</TabsTrigger><TabsTrigger value="inProgress">{labels.inProgress}</TabsTrigger><TabsTrigger value="delivered">{labels.delivered}</TabsTrigger><TabsTrigger value="cancelled">{labels.cancelled}</TabsTrigger></TabsList></Tabs><div className="orders-grid">{filteredOrders.map((order) => <OrderCard key={order.id} order={order} labels={labels} onDetails={() => setSelectedOrder(order.id)} onShare={() => setSharing(true)} />)}{!filteredOrders.length && <div className="account-empty"><Truck aria-hidden="true" /><p>{labels.emptyOrders}</p></div>}</div>{selectedOrder && <OrderDetail order={orders.find((item) => item.id === selectedOrder) ?? orders[0]} labels={labels} onClose={() => setSelectedOrder(null)} />}{sharing && <SharePanel labels={labels} onClose={() => setSharing(false)} />}</TabsContent><TabsContent value="information" className="account-content"><InformationPanel labels={labels} saved={saved} onSave={() => { setSaved(true); setTimeout(() => setSaved(false), 2200); }} /></TabsContent></Tabs></div></main>;
}

function OrderCard({ order, labels, onDetails, onShare }: { order: typeof orders[number]; labels: Labels; onDetails: () => void; onShare: () => void }) { return <Card className="order-card"><CardHeader className="order-card-header"><div><CardTitle>{order.id}</CardTitle><span>{order.date}</span></div><Badge className={`status-badge status-${order.status}`}>{labels[order.status]}</Badge></CardHeader><CardContent><div className="order-products">{order.products.map((product, index) => <div className={`product-thumb thumb-${index + 1}`} key={product}><span>{product}</span></div>)}</div><div className="order-card-bottom"><strong>{order.total}</strong><Button variant="ghost" size="sm" onClick={onDetails}>{labels.viewDetails}<ChevronRight data-icon="inline-end" /></Button></div>{order.status === "delivered" && <Button variant="outline" size="sm" className="share-order" onClick={onShare}><Share2 data-icon="inline-start" />{labels.reorder}</Button>}</CardContent></Card>; }

function OrderDetail({ order, labels, onClose }: { order: typeof orders[number]; labels: Labels; onClose: () => void }) { const steps = [labels.confirmed, labels.prepared, labels.shipped, labels.deliveredStep]; return <div className="account-overlay"><Card className="order-detail"><CardHeader><div><span className="section-kicker">{labels.order}</span><CardTitle>{order.id}</CardTitle></div><Button variant="ghost" size="icon" aria-label={labels.close} onClick={onClose}><X /></Button></CardHeader><CardContent><div className="tracking-title"><Truck aria-hidden="true" /><span>{labels.tracking}</span></div><div className="timeline">{steps.map((step, index) => <div className={`timeline-step ${index < 3 ? "is-done" : ""}`} key={step}><span className="timeline-dot">{index < 3 ? <Check /> : index + 1}</span><span>{step}</span></div>)}</div><p className="eta-note">{labels.estimated}</p><div className="detail-products">{order.products.map((product, index) => <div className={`product-thumb thumb-${index + 1}`} key={product}><span>{product}</span></div>)}</div><div className="detail-list"><div><span>{labels.address}</span><strong>Makepe, Douala</strong></div><div><span>{labels.payment}</span><strong>Mobile Money</strong></div><div><span>{labels.subtotal}</span><strong>26 500 FCFA</strong></div><div><span>{labels.shipping}</span><strong>1 500 FCFA</strong></div><div className="detail-total"><span>{labels.total}</span><strong>{order.total}</strong></div></div><Button className="full-button"><ExternalLink data-icon="inline-start" />{labels.followWhatsApp}</Button><Link className="help-link" href="#contact">{labels.needHelp}</Link></CardContent></Card></div>; }

function SharePanel({ labels, onClose }: { labels: Labels; onClose: () => void }) { return <div className="share-drawer"><div className="share-drawer-header"><div><span className="section-kicker">KEMI / SHARE</span><h3>{labels.shareTitle}</h3></div><Button variant="ghost" size="icon" aria-label={labels.close} onClick={onClose}><X /></Button></div><div className="share-product"><div className="product-thumb thumb-1"><span>GABI.</span></div><div><strong>GABI.</strong><span>12 000 FCFA</span></div></div><div className="share-actions"><Button variant="outline"><span className="share-icon">W</span>WhatsApp</Button><Button variant="outline"><span className="share-icon">I</span>Instagram</Button><Button variant="outline" onClick={() => navigator.clipboard?.writeText(window.location.href)}><Copy data-icon="inline-start" />{labels.copyLink}</Button></div></div>; }

function InformationPanel({ labels, saved, onSave }: { labels: Labels; saved: boolean; onSave: () => void }) { return <div className="information-layout"><div className="account-section-heading"><div><span className="section-kicker">04 / 04</span><h2>{labels.information}</h2></div><CircleUserRound aria-hidden="true" /></div><div className="information-grid"><Card><CardHeader><CardTitle>{labels.profile}</CardTitle></CardHeader><CardContent className="profile-fields"><EditableField label={labels.name} value="Daril M." /><EditableField label={labels.phone} value="+237 6XX XXX XXX" /><EditableField label={labels.email} value="nom@exemple.com" /><div className="profile-connection"><span>{labels.connection}</span><strong><span className="google-mark">G</span>{labels.connectedGoogle}</strong></div><Button className="full-button" onClick={onSave}>{saved ? <><Check data-icon="inline-start" />{labels.saved}</> : labels.save}</Button></CardContent></Card><Card><CardHeader><CardTitle>{labels.addresses}</CardTitle></CardHeader><CardContent className="address-list"><AddressCard title="Domicile" address="Makepe, Douala - Cameroun" defaultAddress labels={labels} /><AddressCard title="Bureau" address="Bastos, Yaounde - Cameroun" labels={labels} /><Button variant="outline" className="full-button"><MapPin data-icon="inline-start" />{labels.addAddress}</Button></CardContent></Card></div><div className="account-footer-actions"><Button variant="ghost">{labels.signOut}</Button><Button variant="ghost" className="danger-action">{labels.deleteAccount}</Button></div></div>; }

function EditableField({ label, value }: { label: string; value: string }) { return <div className="editable-field"><div><span>{label}</span><strong>{value}</strong></div><Button variant="ghost" size="sm" aria-label={`${label}: edit`}><Pencil /></Button></div>; }
function AddressCard({ title, address, defaultAddress, labels }: { title: string; address: string; defaultAddress?: boolean; labels: Labels }) { return <div className={`address-card ${defaultAddress ? "is-default" : ""}`}><div className="address-top"><strong>{title}</strong>{defaultAddress && <Badge>{labels.defaultAddress}</Badge>}</div><span>{address}</span><div className="address-actions"><Button variant="link" size="sm">{labels.edit}</Button>{!defaultAddress && <Button variant="link" size="sm">{labels.setDefault}</Button>}<Button variant="link" size="sm" className="danger-action">{labels.delete}</Button></div></div>; }